### PR TITLE
fix(evpn-bridge): update for api dependencies on evpn-gw api

### PR DESCRIPTION
**Pull request by sandersms**
Fixes to enum updates in evpn gw api

### CODE REVIEW

**Review by atulpatel261194 — APPROVED** [review]
LGTM 👍

**Review by artek-koltun — COMMENTED** [review]
Should we also update `ptype` of [this](https://github.com/opiproject/opi-evpn-bridge/blob/50e0484e9efc3e7d428f6fe8ffe884f71e20672f/README.md?plain=1#L40) exemplary command in README?

**Comment by sandersms** [comment]
> Should we also update `ptype` of [this](https://github.com/opiproject/opi-evpn-bridge/blob/50e0484e9efc3e7d428f6fe8ffe884f71e20672f/README.md?plain=1#L40) exemplary command in README?

Nice catch - I missed that one and put the change in to have that covers.

**Review by artek-koltun — APPROVED** [review]
LGTM!

**Pull request merged**
