### PR TITLE
feat(evpn): complete fastpath implementation of new arch

### PR DESCRIPTION
**Pull request by atulpatel261194**
Introducing the complete implementation for fastpath based on the new opi-evpn-br architecture that has been presented to opi-tsc in 15 Feb 2024 [link](https://lists.opiproject.org/g/tsc/wiki/35979)

This PR includes:

- Modular based implementation according to the architecture(https://github.com/opiproject/opi-evpn-bridge/pull/384)
- Netlink Watcher (https://github.com/opiproject/opi-evpn-bridge/pull/385)
- intel e2000 vendor plugin (https://github.com/opiproject/opi-evpn-bridge/pull/386)

This PR  has dependancy on Netlink Watcher( https://github.com/opiproject/opi-evpn-bridge/pull/385) ,  Intel Vendor Plugin(https://github.com/opiproject/opi-evpn-bridge/pull/386). Once these 2 PRs ( https://github.com/opiproject/opi-evpn-bridge/pull/385 , https://github.com/opiproject/opi-evpn-bridge/pull/386 ) get merged, We will rebase current PR (https://github.com/opiproject/opi-evpn-bridge/pull/384) to main. 
The Current  PR (https://github.com/opiproject/opi-evpn-bridge/pull/384) Will be the Last PR to be merged.

### CODE REVIEW

**Comment by mardim91** [comment]
Hello @atulpatel261194 can you please update the description to this one ?

Introducing the complete implementation for fastpath based on the new opi-evpn-br architecture that has been presented to opi-tsc in 15 Feb 2024 [link](https://lists.opiproject.org/g/tsc/wiki/35979)

This PR includes:

Modular based implementation according to the architecture
NetlinkWatcher module
intel e2000 vendor module

**Review by artek-koltun — COMMENTED** [review]
My main question, if it is possible to split the PR to smaller chunks to ease the review process. I see that we can at least organize as separate PRs our preparation steps:
* add of DeInit functionality
* some patch to EventBus with subscribe/unsubscribe
* netlink watcher,
* ...
and finally:
* e2000 plugin

**Comment by mardim91** [comment]
> My main question, if it is possible to split the PR to smaller chunks to ease the review process. I see that we can at least organize as separate PRs our preparation steps:
> 
> * add of DeInit functionality
> * some patch to EventBus with subscribe/unsubscribe
> * netlink watcher,
> * ...
>   and finally:
> * e2000 plugin

Hello @artek-koltun,

The plan that has been presented and agreed by the TSC is to have the two big PRs (drop-0.5 and drop-1.0) first and then for any further development we can make smaller PRs. We have developed the code according that plan. However I understand that it is difficult to review such big PRs in the smallest detail so I think I can discuss with the team to split the drop-1.0 PR in 3 smaller chunks (netlinkWatcher, e2000 plugin and the rest of the code) just to make the review process easier but I cannot go further than that. Of course this will make the testing and bug fixing really hard for us but let me discuss with the team first. If you are ok with that split then maybe we can do it.

**Review by glimchb — CHANGES_REQUESTED** [review]
no vendor code in OPI, please

**Comment by artek-koltun** [comment]
Closing this one, as we agreed: no vendor plugins are allowed in generic domain bridges

**Pull request closed without merging**
